services:
  chrome:
    depends_on:
    - selenium-hub
    environment:
    - SE_EVENT_BUS_HOST=selenium-hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_NODE_SESSION_TIMEOUT=1800
    image: selenium/node-chrome:115.0
    ports:
    - '5900'
    restart: always
    volumes:
    - /dev/shm:/dev/shm
  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub
    ports:
    - 4442:4442
    - 4443:4443
    - 4444:4444
    restart: always
version: '3'
